import { EventEmitter } from "../event-emitter.js";
import { FloatMenu } from "../float-menu.js";
export declare abstract class UIComponent {
    protected emitter: EventEmitter;
    protected view: any;
    protected value: any;
    protected id: string;
    private initialized;
    private attached;
    private disposed;
    private disposers;
    protected menu: FloatMenu;
    constructor(id: string);
    setMenu(menu: FloatMenu): void;
    apply(role: any, theme: any): void;
    getView(): any;
    getValue(): any;
    getId(): string;
    setValue(value: any): void;
    on(event: string, listener: (...args: any[]) => void): () => void;
    off(event: string, listener: (...args: any[]) => void): void;
    protected emit(event: string, ...args: any[]): void;
    protected abstract createView(context: any): void;
    initialize(context: any, menu?: FloatMenu): void;
    protected abstract updateView(): void;
    protected own(dispose: () => void): () => void;
    attach(_container?: any): void;
    detach(): void;
    captureState(): any;
    restoreState(state: any): void;
    dispose(): void;
    get isInitialized(): boolean;
    get isAttached(): boolean;
}
