export declare class LogViewWindow {
    private menu;
    private context;
    private windowManager;
    private theme;
    private logMaxLines;
    private windowRoot;
    private windowParams;
    private titleDragHandle;
    private logView;
    private isCreated;
    private isCreating;
    private isAttached;
    isLogWindowVisible: boolean;
    private _loggerUnsub;
    private _logMaxLinesCache;
    private _logRing;
    private _logHead;
    private _logSize;
    private _logPending;
    private _logFlushScheduled;
    private _onCloseButtonClick;
    private width?;
    private height?;
    lastTouchX: any;
    lastTouchY: any;
    constructor(context: any, theme: any, menu: any, logMaxLines?: number, onCloseButtonClick?: () => void);
    setOnCloseButtonClick(callback: (() => void) | null): void;
    private bindLoggerToLogViewOnce;
    private addLogToView;
    private buildWindowType;
    private createWindowOnce;
    private attachWindowIfNeeded;
    private addDragListener;
    private updatePosition;
    openLogWindow(): void;
    closeLogWindow(): void;
    destroy(): void;
}
